CREATE DATABASE IF NOT EXISTS StarwarsAcademy CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE StarwarsAcademy;
CREATE TABLE IF NOT EXISTS Jedi (JediId INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(200) NOT NULL, JediTypeId TINYINT UNSIGNED NOT NULL, CONSTRAINT CK_Jedi_Type CHECK (JediTypeId IN (1,2,3))) ENGINE=InnoDB;
